# Generated by Django 4.1.5 on 2023-02-17 21:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('nickname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('registerDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration date')),
            ],
        ),
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('addDate', models.DateTimeField(verbose_name='date added')),
                ('permissions', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sshkbase.user')),
            ],
        ),
    ]
