#+TITLE:SSHKBase
#+SUBTITLE: Django app with  CRUD functions, User authentication and Unit testing, Dorset CA 3

* Things stored
This application stores Users and SSHKeys. Each SSH key is tied to a specific user. It could be used with a server hosting files, for example a git server, as a way to easily authenticate users to upload
and get files securely.

Unit tests are present for each view, wether they handle POST requests or not. The coverage is nearly 95% for views, and around 85% for models and forms. Tests are also present to tests models.

Each unit tests tries tests the views without having a user authenticated, then logs a normal user in, and finally logs in with an administrator.

There are 4 test cases :
- ~UserTests~ : These tests check if the User model works correctly. It checks creation, reading, updating and deletion.
- ~SSHKeyTests~ : Same as ~UserTests~, but checks ssh keys.
- ~BasicViewTests~ : Tests views which only render Django templates. They don't modify the database, they only read from it.
  These tests use the views without loging in, logging in as a normal user and as an administrator.
- ~PostHandlerTests~ : Check views which handle POST request, meaning they change the database in some way. Same as basic views, all three possible user types are tested.

